apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: time-coffee
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - name: in-cluster
      namespace: simple-app
      server: https://kubernetes.default.svc
  sourceNamespaces:
    - simple-app
  sourceRepos:
    - https://github.com/avinash221988/kubernetes-coffee-image
  roles:
    - name: read-only
      description: "Read-only access to simple-app"
      policies:
        - p, role:simple-app-read-only, applications, get, time-coffee/simple-app, allow
        - g, avinash, role:simple-app-read-only